// <auto-generated />
namespace MebleShop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedboolpropertytoFeedbacksDb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedboolpropertytoFeedbacksDb));
        
        string IMigrationMetadata.Id
        {
            get { return "201707241423559_added bool property to Feedbacks Db "; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
